----WINDOW FUNCTION----------
--FIND THE TOTAL SALES ACROSS ALL ORDERS

SELECT 
SUM(Sales) TotalSales
FROM Sales.Orders

--FIND THE TOTAL SALES FOR EACH PRODUCT
SELECT 
ProductID,
SUM(Sales) TotalSales
FROM Sales.Orders
GROUP BY ProductID

--FIND THE TOTAL SALES FOR EACH PRODUCts
--ADDITIONALLY PROVIDE DETAILS SUCH ORDER ID , ORDER DATE
SELECT 
OrderID,
OrderDate,
ProductID,
SUM(Sales) OVER(PARTITION BY ProductID, OrderDate) TotalSales
FROM Sales.Orders


--FIND THE TOTAL SALES FOR EACH ORDERS
--ADDITIONALLY PROVIDE DETAILS SUCH ORDER ID , ORDER DATE
SELECT 
OrderID,
OrderDate,
SUM(Sales) OVER() TotalSales
FROM Sales.Orders


--FIND THE TOTAL SALES FOR EACH PRODUCTS
--ADDITIONALLY PROVIDE DETAILS SUCH ORDER ID , ORDER DATE
---FIND THE TOTAL SALES FOR EACH COMBINATION OF PRODUCT AND ORDER STATUS
SELECT 
OrderID,
OrderDate,
ProductID,
OrderStatus,
SUM(Sales) OVER()TotaSales,
SUM(Sales) OVER(PARTITION BY ProductID) SalesByProducts,
SUM(Sales) OVER(PARTITION BY ProductID , OrderStatus) SalesByProductsAndStatus
FROM Sales.Orders

---RANK EACH ORDER BASED ON THEIR SALES FROM HIGHEST TO LOWEST 
---ADDITIONALLY PROVIDE DETAILS SUCH ORDER ID , ORDER DATE

SELECT 
OrderDate,
OrderID,
Sales,
RANK() OVER(ORDER BY Sales DESC) RankSales
FROM Sales.Orders

---FIND THE TOTAL SALES ACCROSS ALL ORDERS AND THE TOTAL SALES FOR EACH PRODUCT
---ADDITIONALLY PROVIDE DETAILS SUCH AS ORDER ID AND ORDER DATE


SELECT 
OrderID,
OrderDate,
Sales,
SUM(Sales) OVER () TotalSales
FROM Sales.Orders